Repository CommaProject/Comma-Back-end, pull requests merged in 2023-05, with the labels that each got.

#31 feat: 플레이리스트 알람 설정 변경 기능 구현 및 프로젝트 구조 변경에 따른 코드 수정
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
  src/docs/asciidoc/main.adoc
  src/docs/asciidoc/playlist.adoc
  src/main/java/com/team/comma/common/constant/ResponseCode.java
  src/main/java/com/team/comma/spotify/playlist/Exception/PlaylistException.java
  src/main/java/com/team/comma/spotify/playlist/controller/PlaylistController.java
  src/main/java/com/team/comma/spotify/playlist/dto/PlaylistRequest.java
  src/main/java/com/team/comma/spotify/playlist/dto/PlaylistResponse.java
  src/main/java/com/team/comma/spotify/playlist/dto/PlaylistTrackArtistResponse.java
  src/main/java/com/team/comma/spotify/playlist/dto/PlaylistTrackResponse.java
  src/main/java/com/team/comma/spotify/playlist/repository/PlaylistRepository.java
  src/main/java/com/team/comma/spotify/playlist/repository/PlaylistTrackRepository.java
  src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
  src/main/java/com/team/comma/spotify/track/repository/TrackRepository.java
  src/main/java/com/team/comma/util/exception/handler/GeneralExceptionHandler.java
  src/test/java/com/team/comma/spotify/playlist/controller/PlaylistControllerTest.java
  src/test/java/com/team/comma/spotify/playlist/repository/PlaylistRepositoryTest.java
  src/test/java/com/team/comma/spotify/playlist/repository/PlaylistTrackRepositoryTest.java
  src/test/java/com/team/comma/spotify/playlist/service/PlaylistServiceTest.java
  src/test/java/com/team/comma/spotify/track/repository/TrackRepositoryTest.java
Labels: enhancement

#35 refactor: track service 추가 및 playlist service 코드 수정
  src/main/java/com/team/comma/spotify/playlist/controller/PlaylistController.java
  src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
  src/main/java/com/team/comma/spotify/track/service/TrackService.java
  src/test/java/com/team/comma/spotify/playlist/controller/PlaylistControllerTest.java
  src/test/java/com/team/comma/spotify/playlist/service/PlaylistServiceTest.java
Labels: invalid

#36 feat: 메인 세팅 API 구현
  src/docs/asciidoc/login.adoc
  src/docs/asciidoc/main.adoc
  src/docs/asciidoc/playlist-track.adoc
  src/docs/asciidoc/playlist.adoc
  src/docs/asciidoc/security.adoc
  src/main/java/com/team/comma/common/constant/ResponseCode.java
  src/main/java/com/team/comma/common/dto/MessageResponse.java
  src/main/java/com/team/comma/spotify/history/repository/HistoryRepository.java
  src/main/java/com/team/comma/spotify/history/repository/HistoryRepositoryCustom.java
  src/main/java/com/team/comma/spotify/playlist/Exception/PlaylistException.java
  src/main/java/com/team/comma/spotify/playlist/controller/PlaylistController.java
  src/main/java/com/team/comma/spotify/playlist/controller/PlaylistTrackController.java
  src/main/java/com/team/comma/spotify/playlist/domain/Playlist.java
  src/main/java/com/team/comma/spotify/playlist/domain/PlaylistTrack.java
  src/main/java/com/team/comma/spotify/playlist/dto/PlaylistTrackRequest.java
  src/main/java/com/team/comma/spotify/playlist/dto/PlaylistTrackSaveRequestDto.java
  src/main/java/com/team/comma/spotify/playlist/dto/PlaylistUpdateRequest.java
  src/main/java/com/team/comma/spotify/playlist/repository/PlaylistRepository.java
  src/main/java/com/team/comma/spotify/playlist/repository/PlaylistRepositoryCustom.java
  src/main/java/com/team/comma/spotify/playlist/repository/PlaylistRepositoryImpl.java
  src/main/java/com/team/comma/spotify/playlist/repository/PlaylistTrackRepository.java
  src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
  src/main/java/com/team/comma/spotify/playlist/service/PlaylistTrackService.java
  src/main/java/com/team/comma/spotify/search/dto/ArtistResponse.java
  src/main/java/com/team/comma/spotify/track/repository/TrackRepository.java
  src/main/java/com/team/comma/user/repository/UserRepository.java
  src/main/java/com/team/comma/util/auth/service/CustomOAuth2UserService.java
  src/main/java/com/team/comma/util/exception/handler/GeneralExceptionHandler.java
  src/main/java/com/team/comma/util/jwt/service/CustomUserDetailService.java
  src/main/java/com/team/comma/util/jwt/support/CreationCookie.java
  src/main/java/com/team/comma/util/s3/controller/FileUploadController.java
  src/test/java/com/team/comma/spotify/playlist/controller/PlaylistControllerTest.java
  src/test/java/com/team/comma/spotify/playlist/controller/PlaylistTrackControllerTest.java
  src/test/java/com/team/comma/spotify/playlist/repository/PlaylistRepositoryTest.java
  src/test/java/com/team/comma/spotify/playlist/repository/PlaylistTrackRepositoryTest.java
  src/test/java/com/team/comma/spotify/playlist/service/PlaylistServiceTest.java
  src/test/java/com/team/comma/spotify/playlist/service/PlaylistTrackServiceTest.java
  src/test/java/com/team/comma/spotify/search/controller/SearchControllerTest.java
  src/test/java/com/team/comma/spotify/track/repository/TrackRepositoryTest.java
Labels: documentation

#41 refactor: 플레이리스트 삭제 기능 구현 오류 수정
  src/docs/asciidoc/playlist.adoc
  src/main/java/com/team/comma/common/constant/ResponseCode.java
  src/main/java/com/team/comma/common/constant/ResponseCodeEnum.java
  src/main/java/com/team/comma/spotify/playlist/controller/PlaylistController.java
  src/main/java/com/team/comma/spotify/playlist/domain/Playlist.java
  src/main/java/com/team/comma/spotify/playlist/repository/PlaylistRepository.java
  src/main/java/com/team/comma/spotify/playlist/repository/PlaylistRepositoryCustom.java
  src/main/java/com/team/comma/spotify/playlist/repository/PlaylistRepositoryImpl.java
  src/main/java/com/team/comma/spotify/playlist/service/PlaylistService.java
  src/main/java/com/team/comma/spotify/track/service/TrackService.java
  src/main/java/com/team/comma/util/exception/handler/GeneralExceptionHandler.java
  src/main/resources/schema-dev.sql
  src/main/resources/schema-local.sql
  src/test/java/com/team/comma/spotify/playlist/controller/PlaylistControllerTest.java
  src/test/java/com/team/comma/spotify/playlist/repository/PlaylistRepositoryTest.java
  src/test/java/com/team/comma/spotify/playlist/repository/PlaylistTrackRepositoryTest.java
  src/test/java/com/team/comma/spotify/playlist/service/PlaylistServiceTest.java
  src/test/java/com/team/comma/spotify/track/repository/TrackRepositoryTest.java
Labels: invalid
