Repository CommaProject/Comma-Back-end, pull requests merged in 2023-04, with the labels that each got.

#8 feat: 프로젝트 리팩토링
  build.gradle
  settings.gradle
  src/main/java/com/team/comma/CommaApplication.java
  src/main/java/com/team/comma/SecurityConfig.java
  src/main/java/com/team/comma/ServletInitializer.java
  src/main/java/com/team/comma/config/SecurityConfig.java
  src/main/java/com/team/comma/constant/RecommendType.java
  src/main/java/com/team/comma/constant/ResponseCode.java
  src/main/java/com/team/comma/constant/UserRole.java
  src/main/java/com/team/comma/constant/UserType.java
  src/main/java/com/team/comma/domain/Archive.java
  src/main/java/com/team/comma/domain/BaseEntity.java
  src/main/java/com/team/comma/domain/FavoriteArtist.java
  src/main/java/com/team/comma/domain/FavoriteGenre.java
  src/main/java/com/team/comma/domain/Following.java
  src/main/java/com/team/comma/domain/Playlist.java
  src/main/java/com/team/comma/domain/Recommend.java
  src/main/java/com/team/comma/domain/RefreshToken.java
  src/main/java/com/team/comma/domain/Token.java
  src/main/java/com/team/comma/domain/Track.java
  src/main/java/com/team/comma/domain/User.java
  src/main/java/com/team/comma/dto/MessageResponse.java
  src/main/java/com/team/comma/dto/RegisterRequest.java
  src/main/java/com/team/comma/entity/UserArtist.java
  src/main/java/com/team/comma/entity/UserEntity.java
  src/main/java/com/team/comma/entity/UserGenre.java
  src/main/java/com/team/comma/entity/UserInfo.java
  src/main/java/com/team/comma/repository/RefreshTokenRepository.java
  src/main/java/com/team/comma/repository/UserRepository.java
  src/main/java/com/team/comma/service/JwtService.java
  src/main/java/com/team/comma/service/OAuthService.java
  src/main/java/com/team/comma/service/SpotifyService.java
  src/main/java/com/team/comma/service/UserService.java
  src/main/java/com/team/comma/util/oauth/IssuanceAccessToken.java
  src/main/java/com/team/comma/util/oauth/RegisterationOAuthUser.java
  src/main/java/com/team/comma/util/security/CreationCookie.java
  src/main/java/com/team/comma/util/security/CustomUserDetailService.java
  src/main/java/com/team/comma/util/security/JwtAuthenticationFilter.java
  src/main/java/com/team/comma/util/security/JwtTokenProvider.java
  src/main/java/com/team/comma/util/spotify/CreationAccessToken.java
  src/main/resources/application-oauth.properties
  src/main/resources/application-oauth.yaml
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/main/resources/schema-local.sql
  src/test/java/com/team/comma/repository/RefreshTokenRepositoryTest.java
  src/test/java/com/team/comma/repository/UserRepositoryTest.java
  src/test/java/com/team/comma/service/JwtServiceTest.java
  src/test/java/com/team/comma/service/OAuthServiceTest.java
  src/test/java/com/team/comma/service/SpotifyServiceTest.java
  src/test/java/com/team/comma/service/UserServiceTest.java
Labels: enhancement

#13 feat: 사용자 플레이리스트 조회 구현
  src/main/java/com/team/comma/controller/PlaylistController.java
  src/main/java/com/team/comma/domain/RefreshToken.java
  src/main/java/com/team/comma/domain/Track.java
  src/main/java/com/team/comma/dto/PlaylistResponse.java
  src/main/java/com/team/comma/dto/PlaylistTrackResponse.java
  src/main/java/com/team/comma/repository/PlaylistRepository.java
  src/main/java/com/team/comma/repository/PlaylistTrackRepository.java
  src/main/java/com/team/comma/repository/TrackRepository.java
  src/main/java/com/team/comma/service/PlaylistService.java
  src/main/resources/application.yaml
  src/test/java/com/team/comma/controller/PlaylistControllerTest.java
  src/test/java/com/team/comma/repository/PlaylistRepositoryTest.java
  src/test/java/com/team/comma/repository/PlaylistTrackRepositoryTest.java
  src/test/java/com/team/comma/repository/TrackRepositoryTest.java
  src/test/java/com/team/comma/service/PlaylistServiceTest.java
Labels: enhancement, good first issue

#28 refactor: Playlist 조회 DTO 및 테스트 코드 수정
  src/main/java/com/team/comma/domain/Playlist.java
  src/main/java/com/team/comma/domain/Track.java
  src/main/java/com/team/comma/dto/PlaylistResponse.java
  src/main/java/com/team/comma/dto/PlaylistTrackArtistResponse.java
  src/main/java/com/team/comma/dto/PlaylistTrackResponse.java
  src/main/java/com/team/comma/service/PlaylistService.java
  src/main/resources/schema-local.sql
  src/test/java/com/team/comma/controller/PlaylistControllerTest.java
Labels: invalid
